# JDK
language: java
jdk:
- openjdk8

# Release builds
before_deploy:
- mvn -DskipTests package
- export jarfilename=$(ls target/purity-*.jar)
deploy:
  provider: releases
  api_key:
    secure: SXSHFebqJ2YsQNXwdt7+c8DHJ4VVaifZO9NhC8CtOuguXhNjF6UkXHNeec7KcUo+V30AbkTYCb8aDJjh0PUAJHnWRWDp6GP6FTthXHImZkXCluh6bydIU5NEizfAp00aACCvLK2xXjBpZovq5GSqNFJ63X+DJ4OWIeTylKS+cTvu8dks7fcQff7JOFQWXUU2XIXMZP1iKfZQug8HNUMGd+HMlBZM5m11QZ7R8hbM1H4leuQZfZdv5p7rJatWnPZpnhqemRCT0+Vupq8WNtaZgmr0v+VAY9T7qIll53LJydVY7hBS4vhlArEYlS4iSnKIZcGl3GYJ7Z+b66/JWjdHEAEL7zJcOuP4NQdqfIacH+1uXKP1nWoSqVEMLUAkCqFTq+i4KDJiuq7z8G2JevPPMg+bBjiZNN4s7QowhEDabGwQ4t0Bj1VwOb4JeHqiP6TGaIjuDoNcRTh2l0tZna/YWA6c2+eitzKkcb9qnzgNSsWuwpktfmieXu0dwcz6LF+EfO0R0YoF/ih2pV3JqnZg28U6cWI4D1xNI4pWnbf+r+DEZjsIwAUHHLSLir91xc1Ce8tNPxlLVgvS4s6pMlYpMkex1UXOfzxSJw/C6Aql0SCWor8b8PBCbmPhfQCbReWf7YrpkTRa6OWQvmyo4h+l/upZsRNtcMstFWB4wy9WGac=
  file: "${jarfilename}"
  skip_cleanup: 'true'
  on:
    repo: willhains/purity
    tags: true
env:
  global:
    secure: nQW64Psjd4IlcU2sBaeu6TTMggqy8cU6fi214OZHQ8gSriELkZ5qaRX5Hz66ArvtwT8F050wnBaztj5N5GYuqxvmV67qH2FAtYG5icXuT//XrHfZEZHtTAXEOhdn9Ic/Jxow9IcvBFQKFGJ3Fcply2dfbTgbmBenXFGWhhcOPCFJegqcdm434EqRR2SrjJLSD6kRDWph+q0vbDIKduBj998aZdPab5GI9sfg+HBO9CJNsbUV0b1rhv/ksY1lEsMpgcBembCLGbdojRxo1hpndmES7PVmrzEYdYTEGGsWi6Azy7lPSliYnhtWxJf+YQ99SZQDA/VuelPfPhAK+FBl6ARIiLi9x231bPNknFDx/8e5EF3xXuaOatlOV3OxqAT61AY8akhSomxJ+pfeOtSjERHep2wf4b0SN8IZoFH/7lBgR5FrgE1EQUkPhBidjiwbW6G5wxvQ4Bg/np3Yvg/HqjlKP7JdXf2svgzVHXGlw2dwyKGA4kTXesmuiwfuRWs/OK7S6nVAqQ2knueC6QlNCAucuTQ3wVWEBBhN8Fxnpnqxk1nMOhH9AAqG8LwnfmRMhPsVmtgX9wgbSANlKjHP4Xp9HF8nGBf/SuJXjh+fBzFBzi1fT6lARyhttDN8kVBdAxtEtsRpDW+QxsSM6BoP8EWQANMHogmqJsLhd1PqxPg=
