# JDK
language: java
jdk:
- openjdk8

# Release builds
before_deploy:
- mvn -DskipTests package
- export jarfilename=$(ls target/purity-*.jar)
deploy:
  provider: releases
  api_key:
    secure: pJxPSSTlrd4CMev9AoDEhAqLrMBV3eIu/cEQislGZfmHPIcrrFYwve61oZPKypVLnMnf37hZoYQgs5BU/kVq0oMFY7VFVmd0MXiEaYQTZtwu6EestKpWrRJ2FsCPrvp6ZudtANCapwJncQQWMqM437c4x347fN1COwFVBVOFfDhSXDukwzMovOt15HQLZ7pptqU/7pQ1rc4lOzO7G9KXcwD1voJ6hGA4+7Rj1nTXmlK0EdhPfH6joAr07z2Ekyd+ZltfrPSCIuCaGrsXCZ10t5VjBCeFGi+pUoqHS6qucqsp9cV4TLOYOx8iagEPVSMHcre9reTFVQLRWUGDiC+8YqdB3/gmU7kJraRiM1v4GDzNFqHG4KXC1HsHWTPxK8gRkIP4cAj/3O4cZeeWrMDxqyytc+5DnQ4V6OdNfC5k6DltWRIv035n7/n0paq5OaVGBf8t6XSCeFYjWSXPyd15g1g7sF2T04DAl79dBWLbRSS9uQsyi8T6ftLfcmT4Aw+o9/b2GGH/5BB0LyHXJdW9fJdCo+Ch4T+gt8JfToq075eSrCTT3Tpx1tA8tJZ/pXHkE3QRvaco/ePb5oxrtqJ2J4JN7Wz2loKZBP+sn2CVYOhuIozV1UWeS0gbfUujIT9VSFVW13RErSW+PFbH/yoxGfA4h3D5faK5W8+oIOd78lo=
  file: "${jarfilename}"
  skip_cleanup: true
  on:
    repo: willhains/purity
    tags: true
env:
  global:
    secure: nQW64Psjd4IlcU2sBaeu6TTMggqy8cU6fi214OZHQ8gSriELkZ5qaRX5Hz66ArvtwT8F050wnBaztj5N5GYuqxvmV67qH2FAtYG5icXuT//XrHfZEZHtTAXEOhdn9Ic/Jxow9IcvBFQKFGJ3Fcply2dfbTgbmBenXFGWhhcOPCFJegqcdm434EqRR2SrjJLSD6kRDWph+q0vbDIKduBj998aZdPab5GI9sfg+HBO9CJNsbUV0b1rhv/ksY1lEsMpgcBembCLGbdojRxo1hpndmES7PVmrzEYdYTEGGsWi6Azy7lPSliYnhtWxJf+YQ99SZQDA/VuelPfPhAK+FBl6ARIiLi9x231bPNknFDx/8e5EF3xXuaOatlOV3OxqAT61AY8akhSomxJ+pfeOtSjERHep2wf4b0SN8IZoFH/7lBgR5FrgE1EQUkPhBidjiwbW6G5wxvQ4Bg/np3Yvg/HqjlKP7JdXf2svgzVHXGlw2dwyKGA4kTXesmuiwfuRWs/OK7S6nVAqQ2knueC6QlNCAucuTQ3wVWEBBhN8Fxnpnqxk1nMOhH9AAqG8LwnfmRMhPsVmtgX9wgbSANlKjHP4Xp9HF8nGBf/SuJXjh+fBzFBzi1fT6lARyhttDN8kVBdAxtEtsRpDW+QxsSM6BoP8EWQANMHogmqJsLhd1PqxPg=
